<a href="https://colab.research.google.com/github/uppupushpa/practice/blob/main/Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Mean Squared Error
from sklearn.metrics import mean_squared_error
actual=[10,20,30]
predicted=[12,18,35]
loss=mean_squared_error(actual,predicted)
print(loss)

11.0


In [2]:
#Binary Cross Entropy
from sklearn.metrics import log_loss
actual=[1,0,1]
prediction=[0.9,0.2,0.8]
print(log_loss(actual,prediction))

0.18388253942874858


In [3]:
from tensorflow.keras.losses import CategoricalCrossentropy

In [4]:
#Backward Propagation
#Initial values
weight = 2.5
gradient=0.8
learning_rate=0.1

new_weight=weight - learning_rate * gradient

print("Old Weight:", weight)
print("Gradient:", gradient)
print("New Weight:", new_weight)

Old Weight: 2.5
Gradient: 0.8
New Weight: 2.42


In [5]:
#Gradient Descent
weight=5
gradient=3
learning_rate=0.1

for epoch in range(5):
  weight=weight - learning_rate * gradient
  print(f"Epoch {epoch+1}: Weight = {weight:.2f}")

Epoch 1: Weight = 4.70
Epoch 2: Weight = 4.40
Epoch 3: Weight = 4.10
Epoch 4: Weight = 3.80
Epoch 5: Weight = 3.50


In [6]:
# ==========================================
# Building a Neural Network using TensorFlow/Keras
# Example: Predict Pass/Fail based on Study Hours
# ==========================================

# Step 1: Import Libraries
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

# ------------------------------------------
# Step 2: Create Dataset
# ------------------------------------------

# Input (Study Hours)
X = np.array([
    [2],
    [4],
    [6],
    [8],
    [10]
])

# Output (0 = Fail, 1 = Pass)
y = np.array([
    0,
    0,
    1,
    1,
    1
])

# ------------------------------------------
# Step 3: Build Neural Network
# ------------------------------------------

model = Sequential([
    Dense(8, activation='relu', input_shape=(1,)),   # Hidden Layer 1
    Dense(4, activation='relu'),                     # Hidden Layer 2
    Dense(1, activation='sigmoid')                   # Output Layer
])

# ------------------------------------------
# Step 4: Compile the Model
# ------------------------------------------

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# ------------------------------------------
# Step 5: Train the Model
# ------------------------------------------

print("Training Started...\n")

history = model.fit(
    X,
    y,
    epochs=100,
    verbose=1
)

print("\nTraining Completed!")

# ------------------------------------------
# Step 6: Evaluate the Model
# ------------------------------------------

loss, accuracy = model.evaluate(X, y, verbose=0)

print("\nModel Evaluation")
print("-----------------------")
print("Loss     :", round(loss, 4))
print("Accuracy :", round(accuracy * 100, 2), "%")

# ------------------------------------------
# Step 7: Make Predictions
# ------------------------------------------

print("\nPredictions")
print("-----------------------")

test_data = np.array([
    [3],
    [5],
    [7],
    [9]
])

predictions = model.predict(test_data)

for hours, pred in zip(test_data, predictions):
    probability = pred[0]

    if probability >= 0.5:
        result = "Pass"
    else:
        result = "Fail"

    print(f"Study Hours: {hours[0]} -> Probability: {probability:.4f} -> Prediction: {result}")

# ------------------------------------------
# Step 8: Model Summary
# ------------------------------------------

print("\nModel Summary")
print("-----------------------")
model.summary()

# ------------------------------------------
# Step 9: Display Weights and Biases
# ------------------------------------------

print("\nModel Weights and Biases")
print("-----------------------")

for i, layer in enumerate(model.layers):
    weights, biases = layer.get_weights()

    print(f"\nLayer {i+1}")
    print("Weights:")
    print(weights)

    print("Biases:")
    print(biases)

# ------------------------------------------
# Step 10: Predict for a New Student
# ------------------------------------------

study_hours = 3

prediction = model.predict(np.array([[study_hours]]))

print("\nNew Student Prediction")
print("-----------------------")
print("Study Hours :", study_hours)
print("Probability :", prediction[0][0])

if prediction[0][0] >= 0.5:
    print("Final Prediction : PASS")
else:
    print("Final Prediction : FAIL")

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Training Started...

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.6000 - loss: 0.5344
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 204ms/step - accuracy: 0.6000 - loss: 0.5335
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.6000 - loss: 0.5327
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.6000 - loss: 0.5319
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.6000 - loss: 0.5312
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6000 - loss: 0.5305
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6000 - loss: 0.5299
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6000 - loss: 0.5293
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6000 - loss: 0.5288
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.6000 - loss: 0.5283
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6000 - loss: 0.5278
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - a

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 8)              │            16 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 173 (696.00 B)

 Trainable params: 57 (228.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 116 (468.00 B)


Model Weights and Biases
-----------------------

Layer 1
Weights:
[[-0.06606776  0.37334636  0.17928602  0.39576754 -0.77721864 -0.20650905
   0.45282418 -0.76028913]]
Biases:
[ 0.         -0.09844458 -0.10666312 -0.09885435  0.          0.
  0.10109109  0.        ]

Layer 2
Weights:
[[-6.5140843e-02 -3.3590019e-02  2.0288634e-01  5.6231672e-01]
 [ 4.5502642e-01  4.8244128e-01 -3.4342399e-01 -3.9344874e-01]
 [ 8.1050716e-02 -6.7885965e-01  1.9079369e-01  8.5957289e-02]
 [ 6.9878620e-01  1.7719644e-01  3.5453260e-02 -8.3036184e-02]
 [ 4.1865784e-01 -1.6856194e-04 -3.6651674e-01  5.6937891e-01]
 [-1.6265428e-01 -5.2797931e-01  6.3706523e-01  6.0280818e-01]
 [-1.6502173e-01  3.5267033e-02 -1.1426586e-01 -4.4618812e-01]
 [ 5.9170514e-01  5.8684331e-01 -1.1249185e-02  5.8494276e-01]]
Biases:
[-0.09844225  0.10270492  0.          0.        ]

Layer 3
Weights:
[[ 0.69516724]
 [-0.18002602]
 [-1.0516171 ]
 [ 0.07472908]]
Biases:
[-0.09732702]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step

New Studen