<a href="https://colab.research.google.com/github/uppupushpa/practice/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [21]:
arr1=([1,2,3,4])
print(arr1)
arr2=([1,2,3,4],[5,6,7,8])
print(arr2)

#np.arrange(start,atop,step)
arrange=np.array([1,2,3])
print(arrange)

#np.zeros((m,n))
zero=np.zeros((4,6))
print('zeo array : ',zero)

#np.ones((m,n))
one=np.ones((3,3))
print('ones array : ',one)

#np.eye(n)
identity=np.eye(4,4)
print(identity)

#np.linspace(start,stop,num)
ls=np.linspace(1,3,5)
print(ls)

#np.random.rand(m,n)
randnum=((np.random.rand(2,3))*10).astype(int)
print(randnum)

#np.shape()
arshap1=np.shape(arr1)
print(arshap1)
arshap2=np.shape(arr2)
print(arshap2)

#np.reshape()
arr=np.arange(2,10).reshape(4,2)
print(arr)

[1, 2, 3, 4]
([1, 2, 3, 4], [5, 6, 7, 8])
[1 2 3]
zeo array :  [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
ones array :  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[1.  1.5 2.  2.5 3. ]
[[4 2 8]
 [4 3 6]]
(4,)
(2, 4)
[[2 3]
 [4 5]
 [6 7]
 [8 9]]


In [22]:
array1 = ([1,2,3,4],[5,6,7,8])
array2 = ([4,6,8,3],[2,5,7,9])
addition = np.sum(array2)
print(addition)

Mean = np.mean(array1)
print(Mean)

standard = np.std(array1)
print(standard)

Min = np.min(array1)
print(Min)
Max = np.max(array1)
print(Max)

ArgMin = np.argmin(array1)
print(ArgMin)

ArgMax = np.argmax(array1)
print(ArgMax)

X = np.array(([3,4],[5,6]))
Y = np.array(([8,9],[6,7]))
Dot = np.dot(X,Y)
print(Dot)

mat = np.arange(2,10).reshape(2,4)
print(mat)
print(mat.T)

sorts = np.sort(array2)
print(sorts)

44
4.5
2.29128784747792
1
8
0
7
[[48 55]
 [76 87]]
[[2 3 4 5]
 [6 7 8 9]]
[[2 6]
 [3 7]
 [4 8]
 [5 9]]
[[3 4 6 8]
 [2 5 7 9]]


In [23]:
#Practice questions Assignment
arr1=np.array([1,20])
print(arr1)

[ 1 20]


In [24]:
#create a numpy array containing numbers from 1 to 20 using inbuilt function
arr1=np.arange(1,21,1)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [25]:
#create an array of all zeros with 10 elements and convert it to matrix
arr=np.zeros(10)
matrix=arr.reshape(2,5)
print(matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [28]:
#create an array containing even numbers from 2 to 20
arr=np.arange(2,21,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [29]:
#create an array and find number od dimensions,shape,size,datatype and multiply every element by 2
arr=np.array([1,2,3,4,5])
print("Dimensions:",arr.ndim)
print("Shape:",arr.shape)
print("Size:",arr.size)
print("Data Type:",arr.dtype)
print("After mulplying by 2:",arr*2)

Dimensions: 1
Shape: (5,)
Size: 5
Data Type: int64
After mulplying by 2: [ 2  4  6  8 10]


In [30]:
#create an array and find number od dimensions,shape,size,datatype and multiply every element by 2
arr = np.array([10, 20, 30, 40, 50])

print("Sum =", arr.sum())
print("Mean =", arr.mean())
print("Max =", arr.max())
print("Min =", arr.min())

Sum = 150
Mean = 30.0
Max = 50
Min = 10
